### ISSUE TITLE
SP200 Issues

### ISSUE THREAD

**Issue by samtempledev** [Paulie-P/SonarInterface#2]
I would like to get this working for the SP200, I have changed the length from 340 to 360

`if re.search(b'length 360', row.rstrip()):`

But when using the function:

`python3 init.py `

and

`python3 listen.py`

I can see the init message: 

`Connected to SP100. Sending packet requests...`

But on running listen.py in a separate terminal I get:

```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on wlp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
```
Once I interrupt this with Ctrl+C, I get:

```
^C164 packets captured
167 packets received by filter
0 packets dropped by kernel
Traceback (most recent call last):
  File "listen.py", line 36, in <module>
    awaitREDYFX()
  File "listen.py", line 10, in awaitREDYFX
    for row in iter(p.stdout.readline, b''):
KeyboardInterrupt
```
I get the same message regardless of whether I start the app on my phone before or not...

**Comment by Hommus** [comment]
I don't have access to an SP200 just yet, but I have one on order. When it arrives I'm going to use the following process to update my code, feel free to use it earlier for yourself:
1. Capture the packet data between the mobile app and the SP200
2. Open it in Wireshark for analysis
3. Look for any changes in the handshake protocol. If so, update the messages and/or the timing in init.py
4. Look for any changes in where the data appears in the data packets. If so, update the locations in listen.py. I've never used a dual-beam sonar before but for this reason, I imagine there will be additional data to capture.

**Comment by NPageau** [comment]
Hi, I am too trying to read data from the Vexilar T-BOX sp200 with my RPI. Any success from your side?
I have found this document, [https://github.com/jim-mckeown/SP200A-Client/blob/main/SP200AProtocol_20221223.pdf](url)
but I am still unable to extract the depth value from wifi data.
Any help would be appreciated. Thanks
